version: '3.8'

services:
  su-takip-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./server/su-takip.db:/app/server/su-takip.db
    restart: unless-stopped
